// @vitest-environment jsdom
import '../setup';
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { afterEach, expect, test, vi } from 'vitest';
import { CandidatePanel } from '../../apps/studio/src/App';
import type { CandidateGenerationReport, CandidatePreflight } from '../../packages/candidate-generation/src/types';
import type { FeatureSliceArtifact } from '../../packages/source-analysis/src/types';

afterEach(()=>{cleanup();vi.restoreAllMocks();});
function artifact(id:string,branch:string,status:'resolved'|'partial'='resolved'):FeatureSliceArtifact{return{analysisId:id.repeat(16).slice(0,16),relativePath:`.ums/analysis/${id}/feature-slice.json`,slice:{version:2,repository:{baseRef:'main',branchRef:branch,mergeBaseCommit:'1'.repeat(40),branchCommit:(branch==='left'?'2':'3').repeat(40)},selection:{boundaryId:id,instanceId:`${id}-instance`,repositoryRelativePath:`src/${id}.tsx`,line:1,column:0,componentName:id,exportName:id,branch,previewId:branch==='left'?'left':'right',sessionId:`${id}-session`,generation:1,confidence:'exact'},status,boundary:{original:id,analyzed:id,status:'selected-boundary-sufficient',reason:'ready'},changedFiles:[],includedChanges:[],excludedChanges:[],unresolvedDependencies:[],testFileSlices:[],evidence:[]}};}
const inputs=(status='resolved')=>[{artifact:artifact('a','left'),status,sessionId:'left-session'},{artifact:artifact('b','right'),status,sessionId:'right-session'}];
function preflight(status:'ready'|'refused'='ready'):CandidatePreflight{return{generationId:'f'.repeat(16),plan:{version:1,repository:{baseCommit:'1'.repeat(40),candidateBranch:'combined-result'},sliceIds:['a'.repeat(16),'b'.repeat(16)],operations:status==='ready'?[{id:'op:1',kind:'add-file',sliceIds:['a'.repeat(16)],source:{branchCommit:'2'.repeat(40),path:'src/Feature.tsx',region:null,contentHash:'hash'},target:{path:'src/Feature.tsx',region:null,symbol:null},evidenceEdgeIds:['edge'],precondition:{baseContentHash:null,targetContentHash:null,description:'absent'},postcondition:{expectedContentHash:'hash',description:'present'},detail:'add'}]:[],conflicts:status==='refused'?[{id:'conflict:1',kind:'overlap',path:'src/App.tsx',symbol:'App',sliceIds:['a'.repeat(16),'b'.repeat(16)],operationIds:['one','two'],evidenceEdgeIds:['edge'],reason:'Both slices replace App differently.',manualResolution:'Resolve manually.'}]:[],unresolved:[],status}};}
function report(status:'succeeded'|'failed'|'refused'='succeeded'):CandidateGenerationReport{return{version:1,generationId:'f'.repeat(16),status,stage:status==='succeeded'?'complete':'verify',message:status==='succeeded'?'Candidate registered.':'Verification failed.',repository:{baseCommit:'1'.repeat(40),candidateBranch:'combined-result',candidateCommit:status==='succeeded'?'4'.repeat(40):undefined,candidateTree:status==='succeeded'?'5'.repeat(40):undefined,idempotent:true},sliceIds:['a'.repeat(16),'b'.repeat(16)],plan:preflight().plan,appliedOperations:[{operationId:'op:1',path:'src/Feature.tsx',status:'applied',resultingContentHash:'hash',detail:'add'}],excludedSourceChanges:[],conflicts:[],verification:[{name:'typecheck',command:'npm run typecheck',status:status==='succeeded'?'passed':'failed',exitCode:status==='succeeded'?0:1,outputTail:''}],cleanup:{worktreeRemoved:true,processesStopped:true,detail:'clean'},relativePath:'.ums/generation/f/candidate-report.json'};}

test('blocks generation without two current resolved slices and invalidates on stale input',async()=>{const{rerender}=render(<CandidatePanel inputs={[inputs()[0]]} onLaunch={()=>{}}/>);expect(screen.getByText(/Two current resolved slices/)).toBeVisible();expect(screen.getByRole('button',{name:'Prepare candidate plan'})).toBeDisabled();rerender(<CandidatePanel inputs={inputs('partial')} onLaunch={()=>{}}/>);expect(screen.getByRole('button',{name:'Generate candidate'})).toBeDisabled();});
test('shows a ready plan, progress stages, successful audit, verification, idempotence, and launch',async()=>{const launch=vi.fn();vi.spyOn(globalThis,'fetch').mockResolvedValueOnce(new Response(JSON.stringify(preflight()),{status:200,headers:{'Content-Type':'application/json'}})).mockResolvedValueOnce(new Response(JSON.stringify(report()),{status:200,headers:{'Content-Type':'application/json'}}));render(<CandidatePanel inputs={inputs()} onLaunch={launch}/>);fireEvent.click(screen.getByRole('button',{name:'Prepare candidate plan'}));expect(await screen.findByRole('heading',{name:'Preflight: ready'})).toBeVisible();expect(screen.getByText(/1 operations across 1 files/)).toBeVisible();fireEvent.click(screen.getByRole('button',{name:'Generate candidate'}));expect(await screen.findByRole('heading',{name:'Generation succeeded'})).toBeVisible();expect(screen.getByText('typecheck:')).toBeVisible();expect(screen.getByText(/idempotent/)).toBeVisible();expect(screen.getByText(/Worktree\/process cleanup:/)).toBeVisible();expect(screen.getByText('src/Feature.tsx')).toBeVisible();for(const stage of ['validate','plan','transform','verify','commit'])expect(screen.getByText(stage)).toBeVisible();fireEvent.click(screen.getByRole('button',{name:'Launch candidate'}));expect(launch).toHaveBeenCalledWith('combined-result');});
test('displays precise preflight conflicts and failed verification without a launch action',async()=>{vi.spyOn(globalThis,'fetch').mockResolvedValueOnce(new Response(JSON.stringify(preflight('refused')),{status:200,headers:{'Content-Type':'application/json'}}));const{unmount}=render(<CandidatePanel inputs={inputs()} onLaunch={()=>{}}/>);fireEvent.click(screen.getByRole('button',{name:'Prepare candidate plan'}));expect(await screen.findByText('Both slices replace App differently.')).toBeVisible();expect(screen.getByRole('button',{name:'Generate candidate'})).toBeDisabled();unmount();vi.restoreAllMocks();vi.spyOn(globalThis,'fetch').mockResolvedValueOnce(new Response(JSON.stringify(preflight()),{status:200,headers:{'Content-Type':'application/json'}})).mockResolvedValueOnce(new Response(JSON.stringify(report('failed')),{status:200,headers:{'Content-Type':'application/json'}}));render(<CandidatePanel inputs={inputs()} onLaunch={()=>{}}/>);fireEvent.click(screen.getByRole('button',{name:'Prepare candidate plan'}));await screen.findByRole('heading',{name:'Preflight: ready'});fireEvent.click(screen.getByRole('button',{name:'Generate candidate'}));expect(await screen.findByRole('heading',{name:'Generation failed'})).toBeVisible();expect(screen.queryByRole('button',{name:'Launch candidate'})).not.toBeInTheDocument();await waitFor(()=>expect(screen.getByText('failed')).toBeVisible());});
