import { useEffect, useRef, useState } from 'react';
import { acceptsPreviewEvent, bridgeVersion, type PreviewMessage, type StudioCommand } from '../../../packages/shared/src/bridge';
import type { BoundarySelection, SelectionRefusal, SourceIdentity } from '../../../packages/shared/src/sourceIdentity';

interface RepositoryResponse { branches: string[]; clean: boolean; active: PreviewSession | null }
interface PreviewSession { branch: string; url: string; origin: string }
function IdentityPanel({ identity, title }: { identity: SourceIdentity | null; title: string }) { return <section className="panel"><h2>{title}</h2>{identity ? <dl><dt>Component</dt><dd>{identity.componentName ?? 'Anonymous'}</dd><dt>Source</dt><dd><code>{identity.repositoryRelativePath}:{identity.line}:{identity.column}</code></dd><dt>Definition boundary</dt><dd><code>{identity.boundaryId}</code></dd><dt>Runtime instance</dt><dd><code>{identity.instanceId}</code></dd><dt>Branch</dt><dd>{identity.branch}</dd><dt>Mapping</dt><dd>{identity.confidence}</dd></dl> : <p className="muted">None</p>}</section>; }

export function App() {
  const iframe = useRef<HTMLIFrameElement>(null); const [repository, setRepository] = useState<RepositoryResponse | null>(null); const [branch, setBranch] = useState(''); const [preview, setPreview] = useState<PreviewSession | null>(null); const [status, setStatus] = useState('Inspecting fixture…'); const [selecting, setSelecting] = useState(false); const [hovered, setHovered] = useState<SourceIdentity | null>(null); const [selected, setSelected] = useState<BoundarySelection | null>(null); const [refusal, setRefusal] = useState<SelectionRefusal | null>(null); const [runtimeError, setRuntimeError] = useState('');
  useEffect(() => { fetch('/api/repository').then(response => response.json()).then((value: RepositoryResponse) => { setRepository(value); setBranch(value.branches.includes('main') ? 'main' : value.branches[0] ?? ''); setStatus(value.clean ? 'Ready' : 'Fixture is dirty'); }).catch(error => setStatus(String(error))); }, []);
  useEffect(() => { const listener = (event: MessageEvent) => { if (!preview) return; const message = acceptsPreviewEvent(event, preview.origin); if (!message || event.source !== iframe.current?.contentWindow) return; handleMessage(message); }; addEventListener('message', listener); return () => removeEventListener('message', listener); }, [preview]);
  function handleMessage(message: PreviewMessage) { if (message.type === 'preview-ready') setStatus('Preview ready'); else if (message.type === 'selection-mode-enabled') setSelecting(true); else if (message.type === 'selection-mode-disabled') setSelecting(false); else if (message.type === 'boundary-hovered') setHovered((message.payload as SourceIdentity | null) ?? null); else if (message.type === 'boundary-selected') { setSelected(message.payload as BoundarySelection); setRefusal(null); } else if (message.type === 'selection-error') setRefusal(message.payload as SelectionRefusal); else if (message.type === 'runtime-error') setRuntimeError((message.payload as { message: string }).message); }
  function send(type: StudioCommand['type'], payload?: unknown) { if (!preview) return; iframe.current?.contentWindow?.postMessage({ version: bridgeVersion, type, payload }, preview.origin); }
  async function startPreview() { setStatus(`Starting ${branch}…`); setSelecting(false); setHovered(null); setRuntimeError(''); setRefusal(null); setSelected(null); const response = await fetch('/api/preview', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ branch }) }); const value = await response.json(); if (!response.ok) { setStatus(`Start failed: ${value.error ?? response.statusText}`); return; } setPreview(value); setStatus('Loading preview…'); }
  function toggleSelection() { send(selecting ? 'disable-selection' : 'enable-selection'); }
  function clear() { send('clear-selection'); setSelected(null); setHovered(null); setRefusal(null); }
  return <div className="studio"><header><p className="eyebrow">Phase 0 falsification experiment</p><h1>Rendered component source mapping</h1></header><section className="controls"><label>Fixture branch<select aria-label="Fixture branch" value={branch} onChange={event => setBranch(event.target.value)}>{repository?.branches.map(name => <option key={name}>{name}</option>)}</select></label><button onClick={startPreview} disabled={!branch || !repository?.clean}>Start / restart preview</button><button onClick={toggleSelection} disabled={!preview}>{selecting ? 'Exit selection mode' : 'Enter selection mode'}</button><button onClick={clear} disabled={!selected && !hovered}>Clear selection</button><span role="status">{status}</span></section>{runtimeError && <div className="error" role="alert">Runtime error: {runtimeError}</div>}{refusal && <div className="error" role="alert"><strong>Mapping refused:</strong> {refusal.reason}<br />{refusal.evidence}{refusal.supportedAncestorAvailable && <span> A supported ancestor is available.</span>}</div>}<div className="content"><section className="preview"><h2>Preview</h2>{preview ? <iframe ref={iframe} title={`${preview.branch} preview`} src={preview.url} /> : <div className="placeholder">Start a branch preview to begin.</div>}</section><aside className="details"><IdentityPanel title="Hovered boundary" identity={hovered} /><IdentityPanel title="Selected boundary" identity={selected?.identity ?? null} />{selected && <section className="panel"><h2>Eligible ancestors</h2>{selected.ancestors.length ? selected.ancestors.map((identity, index) => <button className="ancestor" key={`${identity.instanceId}-${index}`} onClick={() => send('select-ancestor', { index: index + 1 })}>{identity.componentName ?? identity.repositoryRelativePath}</button>) : <p className="muted">No instrumented ancestor.</p>}</section>}</aside></div></div>;
}
