import { useEffect, useMemo, useReducer, useRef, useState, type RefObject } from 'react';
import type { PublicArtifact, PublicCandidate } from '../../../packages/showcase-evidence/src/schema';
import { catalogueFeatures, catalogueManifest, evidenceForScope, recordedRefusal, resolveCatalogueCandidate } from './catalogueEvidence';
import { catalogueProduct, catalogueProducts } from './catalogueProducts';
import {
  candidateKey,
  emptyShowcaseSelection,
  hasQuickViewSelection,
  scopeFromRuntime,
  scopeKey,
  showcaseSelectionReducer,
  type ShowcaseScope
} from './showcaseSelection';

type View = 'landing' | 'compare';
type WorkspaceView = 'branch-a' | 'branch-b' | 'combined';
type InteractionMode = 'play' | 'select';
type EvidenceTab = 'source' | 'dependencies' | 'verification';
const github = 'https://github.com/varun-raj-77/ui-merge-studio';

function Landing({ open }: { open: () => void }) {
  return <main className="catalogue-site">
    <nav className="catalogue-nav">
      <a href="#top" className="catalogue-wordmark"><span>UM</span>UI Merge Studio</a>
      <div><a href="#local">Run locally</a><a href={github} target="_blank" rel="noreferrer noopener">GitHub</a></div>
    </nav>
    <section className="catalogue-hero" id="top">
      <div>
        <p className="eyebrow">Visual branch integration for React</p>
        <h1>Compare React branches. Keep the best parts.</h1>
        <p>Explore live implementations, select supported rendered features, trace them to source, and inspect the exact verified candidate.</p>
        <div className="catalogue-actions"><button onClick={open}>Open comparison workspace</button><a href="#local">Run locally</a><a href={github} target="_blank" rel="noreferrer noopener">View GitHub</a></div>
        <small>Hosted candidates are pre-generated by the same deterministic local engine.</small>
      </div>
      <div className="hero-catalogue" aria-label="Three preview workspace illustration">
        <div className="hero-branch a"><span>Branch A</span><b>Category navigation</b></div>
        <div className="hero-branch b"><span>Branch B</span><b>Product Quick View</b></div>
        <div className="hero-result"><span>Any supported selection set</span><b>Exact verified candidate</b></div>
      </div>
    </section>
    <section className="compact-proof">
      <article><span>01</span><b>Explore first</b><p>Play mode preserves normal application behaviour.</p></article>
      <article><span>02</span><b>Select real scopes</b><p>Inspector mode exposes only source-backed decisions.</p></article>
      <article><span>03</span><b>Verify exact output</b><p>Every visible result resolves to a generated artifact.</p></article>
    </section>
    <section className="local-setup" id="local">
      <p className="eyebrow">Real local engine</p>
      <h2>Use your own React repository.</h2>
      <p>Local mode launches branches in isolated Git worktrees, maps rendered elements to source, writes a deterministic candidate, and runs verification. The hosted workspace replays the complete pre-generated fixture matrix because a public browser cannot access local Git.</p>
      <pre><code>npm ci{'\n'}npm run dev{'\n'}# open http://127.0.0.1:4310/?mode=local</code></pre>
    </section>
  </main>;
}

interface ArtifactFrameProps {
  artifact: PublicArtifact;
  title: string;
  mode: InteractionMode;
  showChanges: boolean;
  selectedScopes: string[];
  onHover?: (scope: string) => void;
  onToggle?: (scope: string) => void;
}

function ArtifactFrame({ artifact, title, mode, showChanges, selectedScopes, onHover, onToggle }: ArtifactFrameProps) {
  const frame = useRef<HTMLIFrameElement>(null);
  const postState = () => frame.current?.contentWindow?.postMessage({ type: 'ums-showcase-mode', mode, showChanges, selectedScopes }, location.origin);
  useEffect(postState, [mode, showChanges, selectedScopes.join(',')]);
  useEffect(() => {
    const listener = (event: MessageEvent) => {
      if (event.origin !== location.origin || event.source !== frame.current?.contentWindow) return;
      if (event.data?.type === 'ums-showcase-ready') postState();
      if (event.data?.type === 'ums-showcase-scope-hover' && typeof event.data.scope === 'string') onHover?.(event.data.scope);
      if (event.data?.type === 'ums-showcase-scope-toggle' && typeof event.data.scope === 'string') onToggle?.(event.data.scope);
    };
    addEventListener('message', listener);
    return () => removeEventListener('message', listener);
  });
  const source = `/catalogue?ums-artifact=${encodeURIComponent(`${artifact.path}index.html`)}`;
  return <iframe ref={frame} src={source} title={title} onLoad={postState} />;
}

function scopeLabel(scope: ShowcaseScope) {
  if (scope.kind === 'feature') return 'Category sidebar';
  return `Quick View · ${catalogueProduct(scope.instanceId)?.name ?? scope.instanceId}`;
}

function EvidenceDialog({ scope, candidate, opener, close }: { scope: ShowcaseScope; candidate: PublicCandidate; opener: RefObject<HTMLElement | null>; close: () => void }) {
  const [tab, setTab] = useState<EvidenceTab>('source');
  const closeButton = useRef<HTMLButtonElement>(null);
  const evidence = evidenceForScope(scope);
  const product = scope.kind === 'feature-instance' ? catalogueProduct(scope.instanceId) : null;
  useEffect(() => {
    closeButton.current?.focus();
    const listener = (event: KeyboardEvent) => { if (event.key === 'Escape') close(); };
    addEventListener('keydown', listener);
    return () => { removeEventListener('keydown', listener); opener.current?.focus(); };
  }, []);
  return <div className="evidence-backdrop" onMouseDown={event => { if (event.target === event.currentTarget) close(); }}>
    <section className="evidence-dialog" role="dialog" aria-modal="true" aria-labelledby="evidence-title">
      <header><div><span>{evidence.branchLabel}</span><h2 id="evidence-title">{scopeLabel(scope)}</h2></div><button ref={closeButton} onClick={close} aria-label="Close technical evidence">×</button></header>
      <div className="evidence-tabs" role="tablist" aria-label="Technical evidence">
        {(['source', 'dependencies', 'verification'] as EvidenceTab[]).map(item => <button key={item} role="tab" aria-selected={tab === item} onClick={() => setTab(item)}>{item}</button>)}
      </div>
      {tab === 'source' && <div className="evidence-pane">
        <p><strong>Rendered scope</strong><span>{product ? `${product.name} · ${product.id}` : 'Feature-level selection'}</span></p>
        <p><strong>React declaration</strong><code>{evidence.selectedBoundary}</code></p>
        <p><strong>Source</strong><code>{evidence.sourceFile}:{evidence.sourceLine}</code></p>
        {evidence.configuration && <p><strong>Instance configuration</strong><code>{evidence.configuration.path}#{evidence.configuration.declaration}</code></p>}
      </div>}
      {tab === 'dependencies' && <div className="evidence-pane evidence-list">
        {evidence.supportingFiles.map(item => <p key={item.path}><code>{item.path}</code><span>{item.reason}</span></p>)}
      </div>}
      {tab === 'verification' && <div className="evidence-pane evidence-list">
        {candidate.verification.map(gate => <p key={gate.id}><strong>✓ {gate.id}</strong><code>{gate.command}</code></p>)}
        <small>Candidate <code>{candidate.buildId}</code> · commit <code>{candidate.candidateCommit.slice(0, 12)}</code></small>
      </div>}
    </section>
  </div>;
}

function TruthDialog({ close }: { close: () => void }) {
  const closeButton = useRef<HTMLButtonElement>(null);
  useEffect(() => { closeButton.current?.focus(); const listener = (event: KeyboardEvent) => { if (event.key === 'Escape') close(); }; addEventListener('keydown', listener); return () => removeEventListener('keydown', listener); }, []);
  return <div className="evidence-backdrop"><section className="evidence-dialog compact" role="dialog" aria-modal="true" aria-labelledby="truth-title">
    <header><div><span>Execution boundary</span><h2 id="truth-title">Local engine, hosted replay</h2></div><button ref={closeButton} onClick={close} aria-label="Close execution information">×</button></header>
    <div className="truth-copy"><p><strong>Local mode</strong> creates Git worktrees and branches, then runs typecheck, focused tests, and a production build.</p><p><strong>Hosted showcase</strong> resolves your selections to one of {catalogueManifest.candidates.length} artifacts pre-generated by that deterministic engine. The browser never claims to create a Git branch.</p></div>
  </section></div>;
}

function PreviewPanel({ view, title, subtitle, artifact, active, mode, showChanges, selectedScopes, hovered, onHover, onToggle, onEvidence, candidateStatus }: {
  view: WorkspaceView;
  title: string;
  subtitle: string;
  artifact: PublicArtifact;
  active: boolean;
  mode: InteractionMode;
  showChanges: boolean;
  selectedScopes: string[];
  hovered: ShowcaseScope | null;
  onHover?: (scope: string) => void;
  onToggle?: (scope: string) => void;
  onEvidence: (scope: ShowcaseScope, opener: HTMLElement) => void;
  candidateStatus?: string;
}) {
  const evidence = hovered ? evidenceForScope(hovered) : null;
  return <article className={`workspace-preview ${active ? 'mobile-active' : ''} ${view === 'combined' ? 'combined-preview' : ''}`} data-view={view}>
    <header><div><span className={`preview-dot ${view}`} /><div><h2>{title}</h2><p>{subtitle}</p></div></div>{candidateStatus && <span className="candidate-badge">{candidateStatus}</span>}</header>
    <div className="artifact-stage"><ArtifactFrame artifact={artifact} title={`${title} live application`} mode={view === 'combined' ? 'play' : mode} showChanges={view === 'combined' ? false : showChanges} selectedScopes={selectedScopes} onHover={onHover} onToggle={onToggle} /></div>
    <footer className={evidence ? 'scope-context active' : 'scope-context'}>
      {evidence && hovered ? <><div><strong>{scopeLabel(hovered)}</strong><code>{evidence.sourceFile}:{evidence.sourceLine}</code></div><button onClick={event => onEvidence(hovered, event.currentTarget)}>Info</button></> : <span>{view === 'combined' ? 'Generated artifact for the active canonical selection key.' : mode === 'play' ? 'Application interactions are live.' : 'Hover or focus a supported source scope.'}</span>}
    </footer>
  </article>;
}

function Comparison({ exit }: { exit: () => void }) {
  const [selection, dispatch] = useReducer(showcaseSelectionReducer, emptyShowcaseSelection);
  const [mode, setMode] = useState<InteractionMode>('play');
  const [showChanges, setShowChanges] = useState(false);
  const [mobileView, setMobileView] = useState<WorkspaceView>('branch-a');
  const [hovered, setHovered] = useState<Record<'branch-a' | 'branch-b', ShowcaseScope | null>>({ 'branch-a': null, 'branch-b': null });
  const initialCandidate = resolveCatalogueCandidate(candidateKey(emptyShowcaseSelection));
  const [candidate, setCandidate] = useState(initialCandidate);
  const [candidateStatus, setCandidateStatus] = useState<'verified' | 'resolving'>('verified');
  const [evidenceScope, setEvidenceScope] = useState<ShowcaseScope | null>(null);
  const [showTruth, setShowTruth] = useState(false);
  const evidenceOpener = useRef<HTMLElement | null>(null);
  const desiredKey = candidateKey(selection);
  const refused = selection.incompatibleProductId && hasQuickViewSelection(selection);
  const selectedScopeKeys = selection.scopes.map(scopeKey);
  const branchAArtifact = catalogueManifest.artifacts.find(item => item.kind === 'branch-a')!;
  const branchBArtifact = catalogueManifest.artifacts.find(item => item.kind === 'branch-b')!;

  useEffect(() => {
    if (refused || candidate.key === desiredKey) return;
    setCandidateStatus('resolving');
    const timer = setTimeout(() => {
      setCandidate(resolveCatalogueCandidate(desiredKey));
      setCandidateStatus('verified');
    }, 180);
    return () => clearTimeout(timer);
  }, [candidate.key, desiredKey, refused]);

  const handleRuntimeScope = (branch: 'branch-a' | 'branch-b', raw: string, toggle = false) => {
    const scope = scopeFromRuntime(raw, catalogueManifest.productIds);
    if (!scope || scope.branch !== branch) return;
    if (toggle) dispatch({ type: 'toggle-scope', scope });
    else setHovered(current => ({ ...current, [branch]: scope }));
  };
  const openEvidence = (scope: ShowcaseScope, opener: HTMLElement) => { evidenceOpener.current = opener; setEvidenceScope(scope); };
  const toggleIncompatible = () => dispatch({ type: 'toggle-incompatible' });
  const quickCount = selection.scopes.filter(scope => scope.featureId === 'product-quick-view').length;
  const scopeSummary = useMemo(() => {
    const parts = [];
    if (selection.scopes.some(scope => scope.featureId === 'category-sidebar')) parts.push('sidebar');
    if (quickCount) parts.push(`${quickCount} Quick View${quickCount === 1 ? '' : 's'}`);
    return parts.length ? parts.join(' + ') : 'baseline';
  }, [selection.scopes, quickCount]);

  return <main className="comparison-shell">
    <header className="workspace-commandbar">
      <button onClick={exit} className="catalogue-wordmark"><span>UM</span><i>UI Merge Studio</i></button>
      <div className="mode-switch" role="group" aria-label="Preview interaction mode"><button aria-pressed={mode === 'play'} onClick={() => setMode('play')}>Play</button><button aria-pressed={mode === 'select'} onClick={() => setMode('select')}>Select</button></div>
      <div className="command-actions">
        <button aria-pressed={showChanges} onClick={() => setShowChanges(value => !value)}>Changed regions</button>
        <button onClick={() => setShowTruth(true)} aria-label="About local and hosted execution">How it runs</button>
        <button className={selection.incompatibleProductId ? 'experimental active' : 'experimental'} disabled={!hasQuickViewSelection(selection)} aria-pressed={selection.incompatibleProductId} onClick={toggleIncompatible}>Try incompatible Product ID</button>
      </div>
    </header>
    <section className="workspace-heading">
      <div><p className="eyebrow">Product Catalogue · comparison workspace</p><h1>Explore, then select what belongs together.</h1></div>
      <p>{mode === 'play' ? 'Play mode keeps both applications fully interactive.' : 'Select mode exposes only engine-supported source scopes.'}</p>
    </section>
    <nav className="mobile-preview-tabs" aria-label="Preview panels">
      {(['branch-a', 'branch-b', 'combined'] as WorkspaceView[]).map(item => <button key={item} aria-pressed={mobileView === item} onClick={() => setMobileView(item)}>{item === 'branch-a' ? 'Branch A' : item === 'branch-b' ? 'Branch B' : 'Combined'}</button>)}
    </nav>
    <section className="preview-workspace">
      <PreviewPanel view="branch-a" title="Branch A" subtitle="Category navigation" artifact={branchAArtifact} active={mobileView === 'branch-a'} mode={mode} showChanges={showChanges} selectedScopes={selectedScopeKeys} hovered={hovered['branch-a']} onHover={scope => handleRuntimeScope('branch-a', scope)} onToggle={scope => handleRuntimeScope('branch-a', scope, true)} onEvidence={openEvidence} />
      <PreviewPanel view="branch-b" title="Branch B" subtitle="Product Quick View" artifact={branchBArtifact} active={mobileView === 'branch-b'} mode={mode} showChanges={showChanges} selectedScopes={selectedScopeKeys} hovered={hovered['branch-b']} onHover={scope => handleRuntimeScope('branch-b', scope)} onToggle={scope => handleRuntimeScope('branch-b', scope, true)} onEvidence={openEvidence} />
      <PreviewPanel view="combined" title="Combined" subtitle={scopeSummary} artifact={candidate.artifact} active={mobileView === 'combined'} mode="play" showChanges={false} selectedScopes={[]} hovered={null} onEvidence={openEvidence} candidateStatus={refused ? 'Refused' : candidateStatus === 'resolving' ? 'Resolving…' : 'Verified candidate'} />
    </section>
    {refused && <section className="contextual-refusal" role="alert">
      <div><span>Unsafe combination refused</span><h2>Product Quick View + numeric Product ID</h2><p>{recordedRefusal.reason}</p><code>{recordedRefusal.contractPath}#{recordedRefusal.contractSymbol}</code></div>
      <div><p>Your {quickCount} Quick View selection{quickCount === 1 ? ' is' : 's are'} preserved. The last verified candidate remains visible until you remove the incompatible source.</p><button onClick={toggleIncompatible}>Remove incompatible selection</button></div>
    </section>}
    <aside className="selection-dock" aria-label="Active source selections">
      <header><div><span>{selection.scopes.length + (selection.incompatibleProductId ? 1 : 0)} active</span><strong>{refused ? 'Candidate refused' : candidateStatus === 'resolving' ? 'Resolving candidate…' : 'Verified candidate'}</strong></div><button onClick={() => dispatch({ type: 'clear' })} disabled={!selection.scopes.length && !selection.incompatibleProductId}>Clear all</button></header>
      <div className="selection-chips">
        {!selection.scopes.length && !selection.incompatibleProductId && <span className="empty-chip">Baseline · no feature scopes selected</span>}
        {selection.scopes.map(scope => <button key={scopeKey(scope)} onClick={() => dispatch({ type: 'remove-scope', scope })} aria-label={`Remove ${scopeLabel(scope)}`}>{scopeLabel(scope)} <b>×</b></button>)}
        {selection.incompatibleProductId && <button className="unsafe-chip" onClick={toggleIncompatible} aria-label="Remove incompatible Product ID">Numeric Product ID · Experimental <b>×</b></button>}
      </div>
      <button className="view-combined" onClick={() => { setMobileView('combined'); document.querySelector('[data-view="combined"]')?.scrollIntoView({ block: 'center' }); }}>View combined</button>
    </aside>
    <p className="selection-live" role="status" aria-live="polite">{refused ? 'Unsafe Product-ID combination refused. Previous selections preserved.' : `${scopeSummary}. Candidate ${candidate.buildId}.`}</p>
    {evidenceScope && <EvidenceDialog scope={evidenceScope} candidate={candidate} opener={evidenceOpener} close={() => setEvidenceScope(null)} />}
    {showTruth && <TruthDialog close={() => setShowTruth(false)} />}
  </main>;
}

export function CatalogueShowcase() {
  const [view, setView] = useState<View>(() => new URLSearchParams(location.search).get('view') === 'compare' ? 'compare' : 'landing');
  const navigate = (next: View) => {
    history.pushState({ catalogueView: next }, '', next === 'compare' ? '?mode=showcase&view=compare' : '?mode=showcase');
    setView(next);
  };
  useEffect(() => {
    const listener = (event: PopStateEvent) => setView(event.state?.catalogueView === 'compare' ? 'compare' : 'landing');
    addEventListener('popstate', listener);
    return () => removeEventListener('popstate', listener);
  }, []);
  return view === 'landing' ? <Landing open={() => navigate('compare')} /> : <Comparison exit={() => navigate('landing')} />;
}
