import generated from './generated/showcaseRun.json';
import { validatePublicShowcaseReport } from '../../../packages/showcase-evidence/src/schema';

/** Generated by `npm run showcase:prepare`; never replace this with curated claims. */
export const showcaseManifest = validatePublicShowcaseReport(generated);
export type { FeatureId as ShowcaseFeatureId, PublicFeature as ShowcaseFeature } from '../../../packages/showcase-evidence/src/schema';
