import { resolve } from 'node:path';
import { parse } from '@babel/parser';
import traverse from '@babel/traverse';
import * as t from '@babel/types';
import { describe, expect, test } from 'vitest';
import { instrumentReactSource, isProjectOwnedReactSource, type StaticBoundaryMetadata } from '../../packages/source-instrumentation/src/instrumentReactSource';

const root = resolve('C:/experiment/repository');
function transform(code: string, file = 'src/Example.tsx') { const result = instrumentReactSource(code, resolve(root, file), { repositoryRoot: root, branch: 'candidate-a' }); expect(result).not.toBeNull(); return result!; }
function metadata(code: string) { const ast = parse(code, { sourceType: 'module', plugins: ['jsx', 'typescript'] }); const values: StaticBoundaryMetadata[] = []; traverse(ast, { JSXAttribute(path) { if (t.isJSXIdentifier(path.node.name, { name: 'data-ums-boundary' }) && t.isJSXExpressionContainer(path.node.value) && t.isStringLiteral(path.node.value.expression)) values.push(JSON.parse(path.node.value.expression.value)); } }); return values; }

describe('generic React source instrumentation', () => {
  test('maps named functions to their definition and named export', () => { const output = transform(`export function TicketHeader(){ return <header data-kind="ticket">Header</header> }`); const [value] = metadata(output.code); expect(value).toMatchObject({ componentName: 'TicketHeader', exportName: 'TicketHeader', repositoryRelativePath: 'src/Example.tsx', line: 1, column: 8, confidence: 'exact' }); expect(output.code).toContain('data-kind'); });
  test('supports typed arrow components, spread props, and event handlers', () => { const output = transform(`type P={onOpen():void}; export const Row=({onOpen,...rest}:P)=><button {...rest} onClick={onOpen}>Open</button>`); expect(metadata(output.code)[0]).toMatchObject({ componentName: 'Row', exportName: 'Row' }); expect(output.code).toContain('...rest'); expect(output.code).toContain('onClick={onOpen}'); });
  test('supports anonymous and named default exports', () => { expect(metadata(transform(`export default () => <main>Hi</main>`).code)[0].exportName).toBe('default'); expect(metadata(transform(`export default function Dashboard(){return <main />}`).code)[0].componentName).toBe('Dashboard'); });
  test('distinguishes nested component definitions without tagging arbitrary nested hosts', () => { const output = transform(`function Child(){return <header><h2>Child</h2></header>} function Parent(){return <aside><Child/><footer>Foot</footer></aside>}`); const values = metadata(output.code); expect(values.map(value => value.componentName)).toEqual(['Child', 'Parent']); });
  test('represents fragment host siblings with one partial definition identity', () => { const values = metadata(transform(`function Pair(){return <><p>A</p><p>B</p></>}`).code); expect(values).toHaveLength(2); expect(values[0].boundaryId).toBe(values[1].boundaryId); expect(values.every(value => value.confidence === 'partial')).toBe(true); });
  test('instruments conditional host roots while preserving repeated usage', () => { const output = transform(`const State=({ok}:{ok:boolean})=>ok?<p>Yes</p>:<p>No</p>; export function List(){return <div><State ok/><State ok={false}/></div>}`); const values = metadata(output.code); expect(values.filter(value => value.componentName === 'State')).toHaveLength(2); expect(values.find(value => value.componentName === 'List')).toBeTruthy(); expect(output.code.match(/<State/g)).toHaveLength(2); });
  test('does not overwrite an existing data attribute', () => { const output = transform(`function Box(){return <div data-source="application">Box</div>}`); expect(output.code).toContain('data-source="application"'); });
  test('excludes dependencies and paths outside the repository', () => { expect(isProjectOwnedReactSource(resolve(root, 'node_modules/lib/View.tsx'), root)).toBe(false); expect(isProjectOwnedReactSource(resolve(root, '../foreign/View.tsx'), root)).toBe(false); expect(instrumentReactSource('export const X=()=> <div/>', resolve(root, 'src/X.ts'), { repositoryRoot: root, branch: 'x' })).toBeNull(); });
  test('produces stable repository-relative identities without fixture knowledge', () => { const code = `export const Card=()=> <article/>`; const first = metadata(transform(code, 'src/ui/Card.tsx').code)[0]; const second = metadata(transform(code, 'src/ui/Card.tsx').code)[0]; expect(first.boundaryId).toBe(second.boundaryId); expect(first.repositoryRelativePath).toBe('src/ui/Card.tsx'); expect(JSON.stringify(first)).not.toMatch(/sidebar|inspector|support-dashboard/i); });
  test('leaves wrapper-only delegation untagged while preserving the descendant transform', () => { const result = instrumentReactSource(`function Child(){return <section/>} function Wrapper(){return <Child/>}`, resolve(root, 'src/W.tsx'), { repositoryRoot: root, branch: 'candidate-a' }); expect(result?.boundaries).toBe(1); expect(metadata(result!.code)[0].componentName).toBe('Child'); });
});
