import { resolve } from 'node:path';
import { describe, expect, test } from 'vitest';
import { CandidateGenerator } from '../../packages/candidate-generation/src/candidateGenerator';
import { findDeclarationRange, parseModule, reconcileExport, reconcileImport, reconstructTestModule, replaceDeclaration } from '../../packages/candidate-generation/src/astTransform';
import { FeatureSliceAnalyzer } from '../../packages/source-analysis/src/featureSliceAnalyzer';
import { GitSourceRepository } from '../../packages/source-analysis/src/gitModel';
import { buildSourceIndex } from '../../packages/source-analysis/src/sourceIndex';
import type { SourceIdentity } from '../../packages/shared/src/sourceIdentity';

const fixture = resolve(import.meta.dirname, '../../fixtures/generated/support-dashboard');
const repository = new GitSourceRepository(fixture);
function selection(branch:string,path:string,line:number,componentName:string,previewId:string):SourceIdentity{return{boundaryId:`${componentName}-boundary`,instanceId:`${componentName}-instance`,repositoryRelativePath:path,line,column:8,componentName,exportName:componentName,branch,previewId,sessionId:`${previewId}-session`,generation:1,confidence:'exact'};}
async function realArtifacts(){const analyzer=new FeatureSliceAnalyzer(fixture);const sidebarCommit=await repository.resolveRef('branch-sidebar');const inspectorCommit=await repository.resolveRef('branch-inspector');return Promise.all([
  analyzer.analyze({baseRef:'main',branchRef:'branch-sidebar',expectedBranchCommit:sidebarCommit,selection:selection('branch-sidebar','src/features/navigation/AppSidebar.tsx',4,'AppSidebar','left')}),
  analyzer.analyze({baseRef:'main',branchRef:'branch-inspector',expectedBranchCommit:inspectorCommit,selection:selection('branch-inspector','src/features/tickets/ActivityFilters.tsx',3,'ActivityFilters','right')})
]);}

describe('candidate transformation utilities',()=>{
  test('reconciles named aliases and exports without duplication and replaces declarations by AST identity',()=>{let code="import { A } from './dep';\nexport function View(){return <A/>}\n";code=reconcileImport(code,'src/View.tsx',{source:'./dep',local:'Renamed',imported:'B',kind:'value',reason:'test'});code=reconcileImport(code,'src/View.tsx',{source:'./dep',local:'Renamed',imported:'B',kind:'value',reason:'test'});code=reconcileExport(code,'src/View.tsx','View','./View');code=reconcileExport(code,'src/View.tsx','View','./View');code=replaceDeclaration(code,'src/View.tsx','View','function View(){return <Renamed/>}');expect(code.match(/Renamed/g)?.length).toBe(2);expect(code.match(/export \{ View \}/g)?.length).toBe(1);expect(findDeclarationRange(code,'src/View.tsx','View')).not.toBeNull();expect(()=>parseModule(code,'src/View.tsx')).not.toThrow();});
  test('reconstructs the real inspector test module without its excluded sorting test',async()=>{const artifacts=await realArtifacts();const artifact=artifacts[1];const index=await buildSourceIndex(repository,artifact.slice.repository.branchCommit);const slice=artifact.slice.testFileSlices.find(item=>item.path==='src/test/inspector.test.tsx')!;const source=await repository.readFile(artifact.slice.repository.branchCommit,slice.path);const output=reconstructTestModule(source,slice.path,index.moduleByPath.get(slice.path)!,slice);expect(output).toContain('filters activity and reports clipboard failure');expect(output).not.toContain('sorts ticket list newest first');expect(output).toContain('@testing-library/react');});
});

test('builds a stable ready plan for the two real resolved slices with no unrelated paths',async()=>{const artifacts=await realArtifacts();const base=await repository.resolveRef('main');const generator=new CandidateGenerator(fixture);const first=await generator.preflight({repositoryRoot:fixture,baseRef:'main',expectedBaseCommit:base,candidateBranch:'combined-result',artifacts,analyzerSchemaVersion:2});const second=await generator.preflight({repositoryRoot:fixture,baseRef:'main',expectedBaseCommit:base,candidateBranch:'combined-result',artifacts,analyzerSchemaVersion:2});expect(first.plan.status,JSON.stringify({unresolved:first.plan.unresolved,conflicts:first.plan.conflicts},null,2)).toBe('ready');expect(second).toEqual(first);const paths=new Set(first.plan.operations.map(item=>item.target.path));expect(paths).toContain('src/features/navigation/AppSidebar.tsx');expect(paths).toContain('src/features/tickets/ActivityFilters.tsx');expect(paths).toContain('src/test/inspector.test.tsx');expect(paths).not.toContain('src/features/tickets/TicketPage.tsx');expect(paths).not.toContain('src/features/tickets/TicketList.tsx');expect(paths).not.toContain('src/utils/sortTickets.ts');expect(first.plan.operations.find(item=>item.target.path==='src/test/inspector.test.tsx')?.kind).toBe('reconstruct-test-file');},90_000);
