import { resolve } from 'node:path';
import { expect, test } from 'vitest';
import { CandidateGenerator } from '../../packages/candidate-generation/src/candidateGenerator';
import { FeatureSliceAnalyzer } from '../../packages/source-analysis/src/featureSliceAnalyzer';
import { GitSourceRepository } from '../../packages/source-analysis/src/gitModel';
import type { SourceIdentity } from '../../packages/shared/src/sourceIdentity';

const fixture=resolve(import.meta.dirname,'../../fixtures/generated/support-dashboard');const repository=new GitSourceRepository(fixture);
function selection(branch:string,path:string,line:number,componentName:string,previewId:string):SourceIdentity{return{boundaryId:`${componentName}-boundary`,instanceId:`${componentName}-instance`,repositoryRelativePath:path,line,column:8,componentName,exportName:componentName,branch,previewId,sessionId:`${previewId}-session`,generation:1,confidence:'exact'};}
async function artifacts(){const analyzer=new FeatureSliceAnalyzer(fixture);const sidebar=await repository.resolveRef('branch-sidebar');const inspector=await repository.resolveRef('branch-inspector');return Promise.all([analyzer.analyze({baseRef:'main',branchRef:'branch-sidebar',expectedBranchCommit:sidebar,selection:selection('branch-sidebar','src/features/navigation/AppSidebar.tsx',4,'AppSidebar','left')}),analyzer.analyze({baseRef:'main',branchRef:'branch-inspector',expectedBranchCommit:inspector,selection:selection('branch-inspector','src/features/tickets/ActivityFilters.tsx',3,'ActivityFilters','right')})]);}

test('generates and verifies the real candidate atomically, then reports an equivalent repeat as idempotent',async()=>{const base=await repository.resolveRef('main');const sourceBefore=await Promise.all(['branch-sidebar','branch-inspector','branch-incompatible-route'].map(ref=>repository.resolveRef(ref)));const generator=new CandidateGenerator(fixture,{artifactRoot:resolve(fixture,'..','..','..')});const request={repositoryRoot:fixture,baseRef:'main',expectedBaseCommit:base,candidateBranch:'combined-result',artifacts:await artifacts(),analyzerSchemaVersion:2};const first=await generator.generate(request);expect(first.status,first.message).toBe('succeeded');expect(first.repository.candidateTree).toBeTruthy();expect(first.verification.map(item=>item.status)).toEqual(['passed','passed','passed','passed','passed']);expect(await repository.git(['rev-parse','combined-result^'])).toBe(base);const planned=[...new Set(first.plan.operations.map(item=>item.target.path))].sort();const changed=(await repository.git(['diff','--name-only','main..combined-result'])).split(/\r?\n/).filter(Boolean).sort();expect(changed).toEqual(planned);const candidateTest=await repository.readFile('combined-result','src/test/inspector.test.tsx');expect(candidateTest).toContain('filters activity and reports clipboard failure');expect(candidateTest).not.toContain('sorts ticket list newest first');expect(await repository.fileExists('combined-result','src/utils/sortTickets.ts')).toBe(false);expect(await repository.readFile('combined-result','src/features/tickets/TicketPage.tsx')).toContain('Support Tickets');const second=await generator.generate(request);expect(second.status,second.message).toBe('succeeded');expect(second.repository.idempotent).toBe(true);expect(second.repository.candidateTree).toBe(first.repository.candidateTree);expect(second.plan).toEqual(first.plan);expect(await Promise.all(['branch-sidebar','branch-inspector','branch-incompatible-route'].map(ref=>repository.resolveRef(ref)))).toEqual(sourceBefore);expect((await repository.git(['worktree','list','--porcelain']))).not.toContain('ui-merge-studio-candidate-');},240_000);
